/**
 * Bộ thủ (Kangxi radical) lookup helpers.
 *
 * Data files (all under src/lib/kanji/, generated by scripts/gen_decomposition.ts except
 * radicals.json and decomposition-overrides.json which are hand-authored):
 *  - radicals.json               214-radical dictionary (Hán-Việt name, meaning, strokes, variants)
 *  - classifying.json            kanji -> KANJIDIC classical (Kangxi) radical NUMBER (1..214)
 *  - decomposition.json          kanji -> raw KRADFILE component chars
 *  - decomposition-overrides.json  kanji -> curated component chars (replaces filtered KRADFILE)
 *
 * Model = "bộ chính + thành phần có nghĩa":
 *  - primary    = the kanji's classifying bộ thủ (always correct, from KANJIDIC)
 *  - components = meaningful chiết tự parts (KRADFILE, cleaned: self-ref dropped, representative
 *                 glyphs normalized, meaningless single strokes removed) — or a manual override.
 */

import type { RadicalInfo } from '$lib/types/kanji';
import radicalsData from './radicals.json';
import classifyingData from './classifying.json';
import decompositionData from './decomposition.json';
import overridesData from './decomposition-overrides.json';

export type { RadicalInfo };

const RADICALS = radicalsData as RadicalInfo[];
const CLASSIFYING = classifyingData as Record<string, number>;
const DECOMPOSITION = decompositionData as Record<string, string[]>;
const OVERRIDES = overridesData as Record<string, unknown>;

/** A resolved bộ thủ component shown in the UI. */
export type Component = {
	char: string; // glyph to display (preferred/canonical form)
	canonical: string; // canonical radical char, or the raw char if not a radical
	hanViet: string | null; // Sino-Vietnamese name (or kanji reading fallback), null if unknown
	meaning: string | null; // Vietnamese gloss, null when only a fallback reading is known
	isRadical: boolean; // true when resolved from the radical dictionary
	isPrimary: boolean; // true for the classifying bộ thủ
};

// Index every canonical char AND every variant form -> its RadicalInfo.
const radicalIndex = new Map<string, RadicalInfo>();
for (const r of RADICALS) {
	radicalIndex.set(r.radical, r);
	for (const v of r.variants ?? []) radicalIndex.set(v, r);
}

// Build a global kanji -> Hán-Việt reading index from the level data files (n1..n5),
// a fallback for decomposition components that are kanji but not dictionary radicals.
type KanjiItem = { word: string; meaning: string };
const kanjiMeaning = new Map<string, string>();
const levelFiles = import.meta.glob<{ default: KanjiItem[] }>('./n[12345].json', { eager: true });
for (const mod of Object.values(levelFiles)) {
	for (const k of mod.default) {
		if (k.word && k.meaning && !kanjiMeaning.has(k.word)) kanjiMeaning.set(k.word, k.meaning);
	}
}

function displayForm(info: RadicalInfo): string {
	return info.display ?? info.radical;
}

// Pure structural stroke-groups (canonical form) that carry no standalone teaching meaning;
// suppressed as components (they can still appear as a kanji's primary classifying bộ).
const NOISE_COMPONENTS = new Set<string>(['亠']);

// KRADFILE picks an ugly "representative" glyph for some radical variants (汁 for the 氵 water
// form, 込 for 辶, etc.). Map those to the clean combining form actually written in kanji, so the
// learner sees a familiar shape. Canonical (and thus the tooltip mapping) is unaffected.
const KRAD_DISPLAY: Record<string, string> = {
	汁: '氵', // THỦY
	込: '辶', // SƯỚC
	化: '亻', // NHÂN
	个: '人', // NHÂN (top form)
	刈: '刂', // ĐAO
	艾: '艹', // THẢO
	礼: '礻', // THỊ
	扎: '扌', // THỦ
	杰: '灬', // HỎA
	阡: '阝', // PHỤ (left)
	邦: '阝' // ẤP (right)
};

// Compound radical (canonical) -> the atomized sub-parts KRADFILE redundantly lists alongside it.
// When the whole is present in a breakdown (as a component OR the primary bộ), these are dropped.
const CONTAINS: Record<string, string[]> = {
	糸: ['幺', '小'],
	元: ['二', '儿'],
	青: ['月', '土', '二'],
	頁: ['貝', '目', '八'],
	穴: ['宀', '八', '儿'], // KRADFILE nests 宀 + 八/儿 inside 穴 (hang); keep 穴 HUYỆT, drop the pieces
	母: ['毋'] // KRADFILE nests 毋 inside 母 (mẹ); keep 母 MẪU, drop the 毋 VÔ artifact
};

/** Pick the glyph to show for a radical component: the variant form actually used in the
 *  breakdown (氵, 攵, 耂), else the canonical/display form. Keeps `canonical` for the mapping. */
function formFor(raw: string, info: RadicalInfo): string {
	if (raw !== info.radical && (info.variants?.includes(raw) ?? false)) return KRAD_DISPLAY[raw] ?? raw;
	return displayForm(info);
}

/** Resolve a single component character to a displayable Component. `preferForm` overrides the
 *  displayed glyph (used for the primary bộ, whose raw lookup is always the canonical char). */
function resolveComponent(raw: string, isPrimary: boolean, preferForm?: string): Component {
	const info = radicalIndex.get(raw);
	if (info) {
		return {
			char: preferForm ?? formFor(raw, info),
			canonical: info.radical,
			hanViet: info.hanViet,
			meaning: info.meaning,
			isRadical: true,
			isPrimary
		};
	}
	const reading = kanjiMeaning.get(raw);
	return {
		char: raw,
		canonical: raw,
		hanViet: reading ?? null,
		meaning: null,
		isRadical: false,
		isPrimary
	};
}

/** Look up a radical (by canonical or variant form). */
export function getRadicalInfo(char: string): RadicalInfo | null {
	return radicalIndex.get(char) ?? null;
}

/** The kanji's classifying bộ thủ (the single official radical), or null if unknown. */
export function getClassifying(kanji: string): RadicalInfo | null {
	const num = CLASSIFYING[kanji];
	if (!num) return null;
	return RADICALS[num - 1] ?? null;
}

/** Meaningful chiết tự components (excluding the primary bộ), from override or filtered KRADFILE. */
function meaningfulComponents(kanji: string, primaryCanonical: string | null): Component[] {
	const override = OVERRIDES[kanji];
	if (Array.isArray(override)) {
		// Trust the curated list verbatim; just resolve + drop the primary if duplicated.
		return (override as string[])
			.map((raw) => resolveComponent(raw, false))
			.filter((c) => c.canonical !== primaryCanonical);
	}

	const raw = DECOMPOSITION[kanji] ?? [];
	const seen = new Set<string>();
	const candidates: { part: string; canonical: string }[] = [];
	for (const part of raw) {
		const info = radicalIndex.get(part);
		const canonical = info ? info.radical : part;

		// Drop self-reference (kanji listing itself as its own component).
		if (canonical === kanji || part === kanji) continue;
		// Keep only meaningful parts (a dictionary radical or a known kanji).
		if (!info && !kanjiMeaning.has(part)) continue;
		// Drop meaningless single-stroke radicals, unless it's the classifying bộ.
		if (info && info.strokes === 1 && canonical !== primaryCanonical) continue;
		// Drop the primary bộ here (shown separately) and dedupe by canonical form.
		if (canonical === primaryCanonical || seen.has(canonical)) continue;
		// Drop pure structural stroke-groups that carry no teaching meaning on their own.
		if (NOISE_COMPONENTS.has(canonical)) continue;

		seen.add(canonical);
		candidates.push({ part, canonical });
	}

	// KRADFILE atomizes some compound radicals, listing both the whole and its pieces
	// (e.g. 糸 alongside 幺 + 小). When the whole is present — as a component OR the primary
	// bộ — drop the redundant pieces.
	const suppressed = new Set<string>();
	if (primaryCanonical) for (const sub of CONTAINS[primaryCanonical] ?? []) suppressed.add(sub);
	for (const c of candidates) {
		for (const sub of CONTAINS[c.canonical] ?? []) suppressed.add(sub);
	}
	return candidates
		.filter((c) => !suppressed.has(c.canonical))
		.map((c) => resolveComponent(c.part, false));
}

/** The form the primary bộ takes inside this kanji: its variant if one appears in the KRADFILE
 *  breakdown (海→氵, 教→攵), otherwise the canonical/display form. */
function primaryFormInKanji(kanji: string, info: RadicalInfo): string {
	const raw = DECOMPOSITION[kanji] ?? [];
	for (const v of info.variants ?? []) if (raw.includes(v)) return KRAD_DISPLAY[v] ?? v;
	return displayForm(info);
}

/** Full bộ thủ breakdown for a kanji: the classifying bộ plus meaningful components. */
export function boThu(kanji: string): { primary: Component | null; components: Component[] } {
	const primaryInfo = getClassifying(kanji);
	const primary = primaryInfo
		? resolveComponent(primaryInfo.radical, true, primaryFormInKanji(kanji, primaryInfo))
		: null;
	const components = meaningfulComponents(kanji, primaryInfo?.radical ?? null);
	return { primary, components };
}

/** Flat list of all bộ thủ parts for a kanji (primary first) — convenient for search. */
export function boThuParts(kanji: string): Component[] {
	const { primary, components } = boThu(kanji);
	return primary ? [primary, ...components] : components;
}

/** Tooltip label for a component, or null when nothing is known about it. */
export function componentLabel(c: Component): string | null {
	if (!c.hanViet) return null;
	const base = c.meaning ? `${c.hanViet} — ${c.meaning}` : c.hanViet;
	// When the shown glyph isn't the canonical radical, reveal the mapping (氵 → 水 THỦY — nước).
	if (c.isRadical && c.char !== c.canonical) return `${c.char} → ${c.canonical} ${base}`;
	return base;
}

// Reverse index: radical canonical char -> app kanji whose bộ thủ breakdown includes it.
const kanjiByRadical = new Map<string, string[]>();
for (const kanji of Object.keys(CLASSIFYING)) {
	for (const part of boThuParts(kanji)) {
		if (!part.isRadical) continue;
		const list = kanjiByRadical.get(part.canonical) ?? [];
		list.push(kanji);
		kanjiByRadical.set(part.canonical, list);
	}
}

/** App kanji whose bộ thủ breakdown contains the given radical (canonical char). */
export function kanjiForRadical(radical: string): string[] {
	return kanjiByRadical.get(radical) ?? [];
}

/** The full 214-radical dictionary, in Kangxi (stroke) order. */
export const ALL_RADICALS: RadicalInfo[] = RADICALS;
